name: broadcast_manager
description: To make broadcast easy!
version: 1.0.2
homepage: https://github.com/CimZzz/broadcast_manager

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
